### ISSUE TITLE
Write a provider for the Chef API

### ISSUE THREAD

**Issue by dustinmm80** [conjurinc/summon#17]
It has been suggested that we write a provider for the Chef API to make the transition from secrets stored in Chef easier.

Maybe we can use this lib https://github.com/marpaia/chef-golang. The provider will take care of decryption

**Comment by dustinmm80** [comment]
This is done: https://github.com/conjurinc/summon-chefapi

**Comment by scalp42** [comment]
@dustinmm80 thanks a lot for the work, greatly appreciated #hugops
