### ISSUE TITLE
Installing the summon-s3 provider

### ISSUE THREAD

**Issue by robgodfrey** [conjurinc/summon#18]
Hi

Possibly a dumb question, but how should the summon-s3 provider be installed? Is it clone from git, build, package and then move the dist package to /usr/libexec/summon/?

Thanks
Rob

**Comment by jjmason** [comment]
Hi Rob,

There are prebuilt packages for OSX, Linux, and Windows available [here](https://github.com/conjurinc/summon-s3/releases).  The easiest way to install them is to just unzip the appropriate archive and place the executable it contains in `/usr/lib/summon`.  

If you want to contribute to the project, your best bet for development work is actually to use `go run main.go` after installing the dependencies with [godep](https://github.com/tools/godep).

The steps you describe are correct, but they are for building a full release (with executables for all three supported platforms).

Hope that helps, and let me know if you have any other questions.

Best,
Jon
