### ISSUE TITLE
Errors when run on Alpine Linux

### ISSUE THREAD

**Issue by chrisdostert** [conjurinc/summon#20]
When attempting to create a [docker image](https://hub.docker.com/r/repworth/summon-s3_provider/) for summon on alpine linux, I am unable to get summon to retrieve secrets. I have only tried the s3 provider. It works just fine if I use ubuntu as a base image rather than Alpine. I'm at a loss and not sure how to debug further. Any ideas? Below is the sh trace

```bin/sh
/ # summon --yaml 'test: !var myorg-creds/test' cat @SUMMONENVFILE
Error fetching variable test: 
```

**Comment by dustinmm80** [comment]
It looks like alpine needs to be a separate release binary

http://www.blang.io/posts/2015-04_golang-alpine-build-golang-binaries-for-alpine-linux/

I'll try this out tomorrow and if it works, add alpine to the build matrix. 
Thanks for contributing, stay tuned :)

**Comment by chrisdostert** [comment]
@dustinmm80 got it to work on Alpine using [this base image](https://hub.docker.com/r/frolvlad/alpine-glibc/). 

The image readme states "contains glibc to enable
proprietary projects compiled against glibc (e.g. OracleJDK, Anaconda) work on Alpine."

**Comment by chrisdostert** [comment]
BTW.. can't say thank you enough for contributing this project.. it's just what i've been looking for. Stellar work!

**Comment by dustinmm80** [comment]
Thank you, glad the project is useful for you :)

I'm going to leave this issue open as a reminder to fix - we use Alpine internally at Conjur as well and it'd be nice to be able to use Summon without requiring a non-standard Alpine base image.

**Comment by dividedmind** [comment]
Actually summon itself seems to work fine, just the s3 provider doesn't. Created an issue there (https://github.com/conjurinc/summon-s3/issues/1), closing this one.
