### ISSUE TITLE
Secrets With Constant Integer Values Not Exported

### ISSUE THREAD

**Issue by chrisdostert** [conjurinc/summon#21]
If in my `secrets.yml` I set the value of a key to an integer the key is not exported

example of exported and not exported specifications in secrets.yml
```yml
EXPORTED: '3306'
NOT_EXPORTED: 3306
```

no error is thrown either way. 
In the erroneous case the only difference is the secret is not exported

**Comment by dustinmm80** [comment]
Good find! 

I just added integer support in https://github.com/conjurinc/summon/commit/764896e7e5bc15f27ef7d0bd059afd084f004dc7

Will publish v0.3.1 binaries tomorrow.

**Comment by dustinmm80** [comment]
Fixed and released in v0.3.1

https://github.com/conjurinc/summon/releases/tag/v0.3.1
