### ISSUE TITLE
/usr/libexec is not writable by default on OSX 10.11.x

### ISSUE THREAD

**Issue by dustinmm80** [conjurinc/summon#23]
This is a problem when installing providers, unless you disable SSI OSX won't let you place them in `/usr/libexec/summon`, the default provider directory. We need to change the default provider dir for OSX.

**Comment by scalp42** [comment]
`/usr/local` would do the trick (where Homebrew is doing it)

**Comment by dustinmm80** [comment]
Summon v0.4.0 fixes this issue. The new default provider path is `/usr/local/lib/summon`. Enjoy!

https://github.com/conjurinc/summon/releases/tag/v0.4.0
