### ISSUE TITLE
Keepass provider

### ISSUE THREAD

**Issue by mskarbek** [conjurinc/summon#27]
I have just created simple provider for Keepass kdbx file - [mskarbek/summon-keepass](https://github.com/mskarbek/summon-keepass).

**Comment by dustinmm80** [comment]
Thanks @mskarbek, this looks great. I'll add it to the docs.

One note - it may be useful if the keepass_db password could be read from an environment variable as well.

**Comment by dustinmm80** [comment]
Your provider is now listed here: http://conjurinc.github.io/summon/#providers
