### ISSUE TITLE
Summon doesn't attach to psql correctly

### ISSUE THREAD

**Issue by dustinmm80** [conjurinc/summon#28]
Launching a subprocess with summon that has flags that summon also has causes summon to fail.

Example:

```
summon psql -p 7432 -h conjur -U postgres
```

summon and psql both use the `-p` flag. summon doesn't know this is a flag for the psql process. This needs to be fixed.

**Comment by kgilpin** [comment]
I like "summon -- cmd"

**Comment by apotterri** [comment]
`summon -- cmd` makes sense to me, too. The `--` should probably be optional, only required if the subcommand needs an overlapping flag.

**Comment by dividedmind** [comment]
It does and it's simple to implement, though OTOH perhaps it should just not parse arguments that come after the command (ie. first non-flag) at all.

**Comment by dustinmm80** [comment]
After looking into this it's not a problem with argument, but rather with `psql` itself. Docker works correctly, for example. Need to investigate more what is different about attaching to `psql`.

**Comment by dustinmm80** [comment]
I'm just going to close this. I haven't run into this in over a year. Someone will create another issue if there is indeed a problem.

**Comment by dividedmind** [comment]
Or reopen. 

BTW, I don't think `wontfix` label applies here: it's for where a problem is acknowledged and identified but the decision is not to fix. Ok to remove?

**Comment by dustinmm80** [comment]
All set, thanks Rafal!

We'll leave this issue closed for now, can always reopen it if needed.
