### ISSUE TITLE
Add installation notes

### ISSUE THREAD

**Issue by ggonchar** [conjurinc/summon#30]
Unless you read documentation from top to bottom It's not clear that except downloading Summon itself it is necessary to download provider implementation in addition and put into `/usr/local/lib/summon/`dir. Please add installation notes section and explain it explicitly. Another option would be to provide friendly installer which will do this automatically

**Comment by dividedmind** [comment]
Hi, thanks for the report! 
I added a tiny note in the README that's hopefully early enough that it's visible; let me know if you think it's enough.

**Comment by ggonchar** [comment]
@dividedmind should be enough, thanks for prompt reaction
