### ISSUE TITLE
Doesn't work on Windows

### ISSUE THREAD

**Issue by dividedmind** [conjurinc/summon#40]
Summon checks for executable bit when executing a provider and fails if it's not present.

Unfortunately, this doesn't work on Windows which doesn't have executable bits.

**Comment by dividedmind** [comment]
I've tested removing the exec bit check and it does allow it to run, but unfortunately summon hangs; it appears as if it can't detect, on Windows, when the child process terminates.

**Comment by dividedmind** [comment]
This might be related to https://github.com/golang/go/issues/18537 though -- I don't have an actual Windows to test on. Can someone with access to Windows please test the [attached binary](https://github.com/conjurinc/summon/files/915022/summon.zip)? Thanks!

**Comment by jdotlu** [comment]
That attached binary works for me with summon-conjur v.0.2.0

**Comment by dividedmind** [comment]
Great, thanks! I'll work on rolling this change in and cut a new release.
