### ISSUE TITLE
Provide an option to export all the env var / secret pairs as an env file

### ISSUE THREAD

**Issue by kgilpin** [conjurinc/summon#5]
For example, the Docker CLI accepts an `--env-file` argument, which is a file containing environment variable names and values.

https://docs.docker.com/reference/commandline/cli/

Cauldron could be instructed to insert an --env-file argument into the sub-command, the value of which would be a temp file containing the secrets in env file format.

**Comment by dustinmm80** [comment]
Implemented in 5154839bae629727b66017b0381352bfcc6089c9
