### ISSUE TITLE
Implement template processing

### ISSUE THREAD

**Issue by kgilpin** [conjurinc/summon#6]
Process a [Go template](http://golang.org/pkg/text/template/), substituting secrets values into the template.

**Comment by veverjak** [comment]
I wouldn't care much for that, there are enough tools that can do that and can read from envs + some backend. 
I use [confd](https://github.com/kelseyhightower/confd) for example.

**Comment by dividedmind** [comment]
Yes, why not keep it simple. There are dedicated tools for that.

**Comment by dustinmm80** [comment]
Perfect! Keeping it simple
